"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DynamicChains = void 0;
var color_1 = require("./color");
exports.DynamicChains = [
    {
        id: "darwinia-parachain",
        nativeTokenUniqueId: "RING",
        name: "Darwinia",
        nodeName: "darwinia2",
        type: "mainnet",
        theme: {
            colors: ["#ff0083", "#F499C0", "#d7d7d7"],
            gradient: (0, color_1.generateGradientColor)('#d7d7d7', '#ff0083', 6),
        },
        gtag: "G-MYEDJ9WZY6",
        rpcNode: "https://rpc.darwinia.network/",
        api: "https://darwinia.webapi.subscan.io",
        domain: "https://darwinia.subscan.io",
        subdomain: ["darwinia"],
        social: {
            telegram: "https://t.me/DarwiniaNetwork",
            twitter: "https://twitter.com/DarwiniaNetwork",
            github: "https://github.com/darwinia-network",
            price: "https://www.coingecko.com/en/coins/darwinia-network-native-token",
            website: "https://darwinia.network/",
            whitePaper: "",
        },
        parachain: {
            id: 2046,
            relaychain: "polkadot",
        },
        metaMaskConfig: {
            chainId: "0x2e",
            chainName: "Darwinia Network",
            nativeCurrency: {
                name: "RING",
                symbol: "RING",
                decimals: 18,
            },
            rpcUrls: ["https://rpc.darwinia.network"],
            blockExplorerUrls: ["https://darwinia.subscan.io"],
        },
        donate: "0x9c0fEf6b48Cb0B16EDc72a61d9503A78782c19e2",
        modules: {
            BOUNTY: false,
            CONTRACT: true,
            CONTRACT_SOURCIFY: true,
            ETH_ADDRESS: true,
            EVM: true,
            EVM_NETWORK: true,
            FELLOWSHIP: false,
            GRANDPA_VOTE: true,
            MULTISIG_TOOL: false,
            NOMINATION_POOL: false,
            NOMINATE_FEATURE: false,
            PARACHAIN: false,
            PARATHREAD: true,
            POLKASSEMBLY_LINK: false,
            PRICE: true,
            PRICE_HISTORY: true,
            PRICE_CONVERT: true,
            REFERENDA_V1: true,
            REFERENDA_V2: true,
            SYSTEM_ACCOUNT: true,
            UNIQUE: false,
            NFT: false,
            V2_REWARD: false,
            VESTING: true,
            STATE_TRACING: false,
            WASM_CONTRACT: false,
            WASM_CONTRACT_SOURCIFY: false,
            // has hide prefix before
            SS58: false,
            TREASURY_CHART: true,
            UNBOND_CHART: true,
            BOND_CHART: true,
            SUPPLY_CHART: true,
            VALIDATOR: false,
            FINALIZEDBLOCK: true,
            GOVERNANCE: true,
            GOVERNANCE_COUNCIL: true,
            GOVERNANCE_TECH: true,
            GOVERNANCE_TREASURY: true,
            GOVERNANCE_TIPS: true,
            GOVERNANCE_BOUNTY: false,
            COLLATOR: false,
        },
        disable: false,
    },
];
